/**
 * Handler: wiki-reindex — regenerate the wiki table of contents.
 *
 * The *only* file this handler writes is ``<root>/.generated/INDEX.md``.
 * Authored pages are enumerated via listPages and grouped by kind.
 * Deterministic output: sorted by kind then path so unchanged wikis yield
 * byte-identical INDEX files.
 *
 * source: mcp_server/handlers/wiki_reindex.py
 */

import { PAGE_KINDS, indexPath } from "../layout.js";
import type { WikiKind } from "../types.js";

const BANNER =
  "<!-- Generated by Cortex wiki-reindex — the authored pages are the source of truth. -->";

export interface WikiReindexResult {
  readonly path: string;
  readonly total_pages: number;
  readonly by_kind: Readonly<Record<string, number>>;
  readonly root: string;
}

export type WikiReindexResponse = WikiReindexResult | { readonly error: string };

export interface WikiReindexDeps {
  readonly wikiRoot: string;
  readonly listPages: (root: string, kind?: WikiKind | null) => Promise<string[]>;
  readonly writeFile: (absPath: string, content: string) => Promise<void>;
  readonly ensureDir: (absDir: string) => Promise<void>;
  readonly joinPath: (...parts: string[]) => string;
}

function renderIndex(grouped: Readonly<Record<string, string[]>>): string {
  const lines: string[] = [BANNER, "", "# Wiki Index", ""];
  const total = Object.values(grouped).reduce((s, ps) => s + ps.length, 0);
  lines.push(`**${total} authored pages across ${PAGE_KINDS.length} kinds.**`);
  lines.push("");
  for (const kind of PAGE_KINDS) {
    const pages = grouped[kind] ?? [];
    lines.push(`## ${kind} (${pages.length})`);
    lines.push("");
    if (!pages.length) {
      lines.push("_No pages yet._");
      lines.push("");
      continue;
    }
    for (const rel of pages) {
      const name = rel.split("/").pop() ?? rel;
      lines.push(`- [${name}](../${rel})`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

export async function handler(
  _args: Record<string, unknown>,
  deps: WikiReindexDeps,
): Promise<WikiReindexResponse> {
  const grouped: Record<string, string[]> = {};
  for (const kind of PAGE_KINDS) {
    try {
      grouped[kind] = await deps.listPages(deps.wikiRoot, kind);
    } catch {
      grouped[kind] = [];
    }
  }

  const content = renderIndex(grouped);
  const target = deps.joinPath(deps.wikiRoot, indexPath());
  const dir = target.split("/").slice(0, -1).join("/");

  try {
    await deps.ensureDir(dir);
    await deps.writeFile(target, content);
  } catch (err) {
    return { error: `reindex failed: ${String(err)}` };
  }

  return {
    path: indexPath(),
    total_pages: Object.values(grouped).reduce((s, ps) => s + ps.length, 0),
    by_kind: Object.fromEntries(Object.entries(grouped).map(([k, v]) => [k, v.length])),
    root: deps.wikiRoot,
  };
}

export const schema = {
  title: "Wiki — reindex",
  description:
    "Regenerate the wiki table of contents at <wiki_root>/.generated/INDEX.md " +
    "by enumerating every authored page and grouping it by kind. " +
    "Output is deterministic — sorted by kind then path. Latency <100ms.",
  inputSchema: {
    type: "object" as const,
    required: [] as const,
    properties: {} as const,
    additionalProperties: false,
  },
} as const;
